const applicants = [
  {
    id: 1,
    firstName: "Jesse",
    lastName: "Raymond",
    state: "Rivers",
  },
  {
    id: 7,
    firstName: "Kendre",
    lastName: "Fidian",
    state: "Ogun",
  },
  {
    id: 9,
    firstName: "Julio",
    lastName: "Klasing",
    state: "Abia",
  },
  {
    id: 8,
    firstName: "Rollins",
    lastName: "Georgeson",
    state: "Rivers",
  },
  {
    id: 2,
    firstName: "Manya",
    lastName: "Siggee",
    state: "Île-de-France",
  },
  {
    id: 3,
    firstName: "Dayna",
    lastName: "Mabey",
    state: "SA",
  },
  {
    id: 4,
    firstName: "Harbert",
    lastName: "Bayford",
    state: "Enugu",
  },
  {
    id: 5,
    firstName: "Ernesto",
    lastName: "Concannon",
    state: "Ohio",
  },
  {
    id: 7,
    firstName: "Kendre",
    lastName: "Fidian",
    state: "Ogun",
  },
  {
    id: 6,
    firstName: "Eli",
    lastName: "Pavlov",
    state: "Mumbai",
  },
  {
    id: 7,
    firstName: "Kendre",
    lastName: "Fidian",
    state: "Ogun",
  },
  {
    id: 6,
    firstName: "Eli",
    lastName: "Pavlov",
    state: "Mumbai",
  },
  {
    id: 10,
    firstName: "Mike",
    lastName: "Evins",
    state: "Lagos",
  },
  {
    id: 8,
    firstName: "Rollins",
    lastName: "Georgeson",
    state: "Rivers",
  },
  {
    id: 1,
    firstName: "Jesse",
    lastName: "Raymond",
    state: "Rivers",
  },
  {
    id: 10,
    firstName: "Mike",
    lastName: "Evins",
    state: "Lagos",
  },
  {
    id: 1,
    firstName: "Jesse",
    lastName: "Raymond",
    state: "Rivers",
  },
  {
    id: 9,
    firstName: "Julio",
    lastName: "Klasing",
    state: "Abia",
  },
  {
    id: 10,
    firstName: "Mike",
    lastName: "Evins",
    state: "Lagos",
  },
  {
    id: 8,
    firstName: "Rollins",
    lastName: "Georgeson",
    state: "Rivers",
  },
  {
    id: 2,
    firstName: "Manya",
    lastName: "Siggee",
    state: "Île-de-France",
  },
  {
    id: 7,
    firstName: "Kendre",
    lastName: "Fidian",
    state: "Ogun",
  },
  {
    id: 1,
    firstName: "Jesse",
    lastName: "Raymond",
    state: "Rivers",
  },  
  {
    id: 1,
    firstName: "Jesse",
    lastName: "Raymond",
    state: "Rivers",
  },  
];

export default applicants;
